// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newway.domain;

import com.newway.domain.Services;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Services_Roo_Configurable {
    
    declare @type: Services: @Configurable;
    
}
