// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newway.domain;

import com.newway.domain.ServicesParameter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ServicesParameter_Roo_Configurable {
    
    declare @type: ServicesParameter: @Configurable;
    
}
